# Generated by Django 5.0.6 on 2024-06-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nevaska_compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='nf_compra',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='nf_venda',
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
