# Generated by Django 5.0.6 on 2024-06-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nevaska_compras', '0002_remove_budget_nf_compra_remove_budget_nf_venda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='Orçamento', max_length=100, null=True),
        ),
    ]
