# Generated by Django 5.0.6 on 2024-06-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nevaska_compras', '0004_alter_company_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('crn_number', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(choices=[('VENDEDOR', 'Vendedor')], default='VENDEDOR', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
