# Generated by Django 5.0.6 on 2024-06-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nevaska_compras', '0005_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
