# Generated by Django 5.0.6 on 2024-06-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nevaska_compras', '0006_supplier_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
